### ISSUE TITLE
Swift compatibility

### ISSUE THREAD

**Issue by depl0y** [ClassyKit/Classy#81]
I am using Classy in a Swift project, and with default controls (like `UICollectionViewCell`) it seems to be working fine. But now I added a subclass of a `UICollectionViewCell` called `SensorCell`. I added an entry to my styling file:

``` css
SensorCell {
    background-color: #f1f1f1;

    UILabel {
        font: $light-font 20;
    }
}
```

Then I get this error:

`2014-09-17 08:43:02.214 HCP[31903:619635] [Classy] -[CASStyler setFilePath:] Error: Error Domain=CASParseErrorDomain Code=2 "Invalid class name`SensorCell`" UserInfo=0x79247260 {CASParseFailingStringErrorKey="
    background-color: #f1f1 ...", NSLocalizedFailureReason=Every selector must have a objectClass, NSLocalizedDescription=Invalid class name`SensorCell`, CASParseFailingLineNumberErrorKey=38}`
